namespace: default
replicaCount: 1

image:
  repository: 192.168.45.131:8080/image-project/validation-worker
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - regcred

service:
  name: ocr-worker

config:
  runMode: test
  rabbitmqHost: rabbitmq-server
  rabbitmqPort: 5672
  consumeExchange: image.request
  consumeQueue: image.validation.request.queue
  consumeRoutingKey: image.validation.request
  dlxExchange: image.request.dead_letter
  dlxRoutingKey: dlx.image.validation.request
  publishExchange: image.response
  publishRoutingKey: image.validation.response
  minioHost: 192.168.45.131
  minioPort: 9000

secrets:
  rabbitmqUser: admin
  rabbitmqPassword: admin
  minioUser: admin
  minioPassword: adminadmin
  databaseUrl: sqlite+aiosqlite:///./test.db
  alembicDatabaseUrl: sqlite:///./test.db
