apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if .Values.addresses }}
  addresses:
  {{- range .Values.addresses }}
    - type: {{ .type | quote }}
      value: {{ .value | quote }}
  {{- end }}
  {{- end }}
  gatewayClassName: {{ .Values.className }}
  listeners:
    - name: {{ .Values.listenerName }}
      port: {{ .Values.port }}
      protocol: HTTP
      {{- if .Values.hostname }}
      hostname: "{{ .Values.hostname }}"
      {{- end }}
      allowedRoutes:
        namespaces:
          from: {{ .Values.allowedRoutesNamespaceFrom }}
