apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  spec:
  storageClassName: ""
  hostPath:
    path: "/home/wjh2012/rabbitmq/data"
  # claimRef:
  # name: persistence-rabbitmq-server-0
  # namespace: default
