apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: minio-ui
  namespace: minio-tenant
spec:
  parentRefs:
    - name: cilium-gw
      namespace: default
      port: 80
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /minio/
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: myminio-console
          namespace: minio-tenant
          port: 9090
